### PR TITLE
ignore some spurious Qt errors when launching sclang

### PR DESCRIPTION
**Pull request by brianlheim**
partial fix for macOS travis builds failing. used in this job: https://travis-ci.org/github/supercollider/supercollider/jobs/730544925

see comments for fuller explanation

### CODE REVIEW

**Comment by brianlheim** [comment]
btw, i've duckduckgo'd these errors and haven't found any info about them at all. the locale file error i'm interpreting as a result of  sclang being run from within the bundle and not by launching the .app itself. the other error(s?) i can't find any info on but it seems like a problem with the chromium base of qtwebengine. i don't see it when running it locally, and i don't know enough about opengl or chromium to venture a guess.

**Comment by brianlheim** [comment]
https://travis-ci.org/github/supercollider/supercollider/jobs/730544925#L5328 is the specific line of the build that shows it's using this branch

**Comment by dyfer** [comment]
Thanks!

I have limited experience with qpm. Why does qpm treat this output as errors? Is the error actually thrown?

**Comment by brianlheim** [comment]
> Why does qpm treat this output as errors? Is the error actually thrown?

qpm treats *anything* written to stderr by sclang as an error, which is totally reasonable in my opinion. when it happens, qpm sees there is something on stderr, then kills the sclang process and throws an error (in python) that terminates qpm.

**Pull request merged**
