### PR TITLE
Call setUpClass & tearDownClass for each test class

### PR DESCRIPTION
**Pull request by patrickdupuis**
I'm not certain this will work as I haven't tested it. @dyfer what do you think?

### CODE REVIEW

**Comment by patrickdupuis** [comment]
https://github.com/supercollider/supercollider/pull/5461

**Comment by dyfer** [comment]
I don't know, I think we should try it. The testing framework is complex and I don't have a full picture of it.

I know this is not documented anywhere, but we're currently running QPM from the branch `topic/xvfb-off`. Could you make this change in a new branch on top of `topic/xvfb-off` and push that branch to this repo? (no PR needed then, I think) Then we'd switch to it in https://github.com/supercollider/supercollider/blob/develop/.github/workflows/actions.yml#L497 and test it in SC's CI.

**Comment by patrickdupuis** [comment]
Ok, I'm testing this branch in my other PR.

**Comment by patrickdupuis** [comment]
The first run was successful over there. It's such a minimal change. Should we merge this into `topic/xvfb-off`?

**Comment by dyfer** [comment]
> The first run was successful over there. It's such a minimal change. Should we merge this into `topic/xvfb-off`?

I'd keep it in a separate branch (and SC repo using that) and consider merging that into `main` eventually. Since I always feel very lost working on qpm I don't have a good idea on whether we want to merge it now or not... I'd cautiously say it sould be fine though.

**Comment by patrickdupuis** [comment]
ok, I have to rename this branch though... one sec

**Pull request closed without merging**
