### PR TITLE
Call setUpClass & tearDownClass for test classes

### PR DESCRIPTION
**Pull request by patrickdupuis**
Redo of #16

### CODE REVIEW

**Comment by patrickdupuis** [comment]
Once we merge this, I'll create a PR for SC that just changes the qpm branch used by the CI. Then, I'll clean up my PR https://github.com/supercollider/supercollider/pull/5461 and then we can merge.

**Comment by dyfer** [comment]
Hm, I don't see changes from the `xvfb-off` branch... sorry if I wasn't clear, I thought we'd pull everything from https://github.com/supercollider/qpm/commits/topic/call-setUpClass-tearDownClass CI definitely needs the updates in `xvfb-off`, I'm just not sure if they are all implemented correctly etc... but it's been working since I changed it months ago.

**Comment by patrickdupuis** [comment]
Sorry, I think I made a mistake with the branches here. Is it better now?

**Comment by patrickdupuis** [comment]
Ah nevermind... we don't even need to merge anything! my bad.

**Pull request closed without merging**
